# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a07779b25ca12958bbbb2262e0a29979344262467dac251a447a8c52fd7e29b84483fde63127a7730e4e6bb7f712d70853f80e1d730dd76b6b9aaa67dc60def2

test:
  secret_key_base: 9e1fef371460184d53e148cfc21fa5e8a5cadd95e422aab3ad9c098306072be5a0d1611b7af4841dfe214f54e8309084be9f19820c74cc5201b1f35c8de105e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
